# Google Cloud Build configuration for Fluid Droplet Template
# This builds and deploys your application to Cloud Run

steps:
  # Build Backend Image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/fluid-droplet-jake/backend:$BUILD_ID'
      - '-f'
      - 'backend/Dockerfile.prod'
      - './backend'
    id: 'build-backend'

  # Build Frontend Image  
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/fluid-droplet-jake/frontend:$BUILD_ID'
      - '-f'
      - 'frontend/Dockerfile.gcp'
      - '--build-arg'
      - 'VITE_API_BASE_URL=https://fluid-droplet-jake-backend-${_SERVICE_SUFFIX}-3h47nfle6q-uc.a.run.app'
      - '--build-arg'
      - 'VITE_FLUID_API_URL=https://fluid-droplet-jake-backend-${_SERVICE_SUFFIX}-3h47nfle6q-uc.a.run.app'
      - '--build-arg'
      - 'VITE_FLUID_ENVIRONMENT=production'
      - '--build-arg'
      - 'VITE_APP_NAME=${_APP_NAME}'
      - './frontend'
    id: 'build-frontend'

  # Push Backend Image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/fluid-droplet-jake/backend:$BUILD_ID'
    id: 'push-backend'

  # Push Frontend Image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/fluid-droplet-jake/frontend:$BUILD_ID'
    id: 'push-frontend'

  # Deploy Backend to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'fluid-droplet-jake-backend-${_SERVICE_SUFFIX}'
      - '--image'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/fluid-droplet-jake/backend:$BUILD_ID'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'NODE_ENV=production,FLUID_API_URL=https://api.fluid.app,LOG_LEVEL=info'
      - '--set-secrets'
      - 'DATABASE_URL=fluid-droplet-jake-DATABASE_URL:latest,FLUID_API_KEY=fluid-droplet-jake-FLUID_API_KEY:latest,FLUID_WEBHOOK_SECRET=fluid-droplet-jake-FLUID_WEBHOOK_SECRET:latest,DROPLET_ID=fluid-droplet-jake-DROPLET_ID:latest,JWT_SECRET=fluid-droplet-jake-JWT_SECRET:latest'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '1'
      - '--max-instances'
      - '10'
    id: 'deploy-backend'

  # Deploy Frontend to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'fluid-droplet-jake-frontend-${_SERVICE_SUFFIX}'
      - '--image'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/fluid-droplet-jake/frontend:$BUILD_ID'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--max-instances'
      - '5'
    id: 'deploy-frontend'

# Substitution variables (can be set in trigger or command line)
substitutions:
  _REGION: 'us-central1'
  _SERVICE_SUFFIX: 'prod'
  _APP_NAME: 'Fluid Droplet'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

timeout: '1200s'
